# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-20 11:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whiskyouaway', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='avgRating',
        ),
    ]
