# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-18 13:03
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('whiskyouaway', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercategories',
            name='title',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Music', 'Music'), ('Animals', 'Animals'), ('Nightlife', 'Nightlife'), ('Sport', 'Sport'), ('Outdoors', 'Outdoors'), ('History', 'History'), ('Family', 'Family'), ('Food', 'Food')], max_length=58),
        ),
    ]
