# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-27 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whiskyouaway', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryContainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Page',
            new_name='Event',
        ),
    ]
