# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-20 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whiskyouaway', '0002_remove_events_avgrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='avgRating',
            field=models.FloatField(null=True),
        ),
    ]
