# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-18 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whiskyouaway', '0002_auto_20190318_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
