# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-06 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whiskyouaway', '0004_review_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='1', unique=True),
            preserve_default=False,
        ),
    ]
