# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-19 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whiskyouaway', '0004_auto_20190319_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='user',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.CharField(max_length=128),
        ),
    ]
