# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-19 16:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whiskyouaway', '0005_auto_20190319_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
    ]
