# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-13 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whiskyouaway', '0006_auto_20190313_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advert',
            name='events',
        ),
        migrations.RemoveField(
            model_name='advert',
            name='user',
        ),
        migrations.AddField(
            model_name='advert',
            name='email',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
