# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-16 12:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('whiskyouaway', '0007_auto_20190313_1856'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('image', models.ImageField(upload_to='static/fish_images')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='Admin', max_length=128)),
                ('name', models.CharField(max_length=128, null=True)),
                ('description', models.CharField(max_length=9999, null=True)),
                ('avgRating', models.FloatField(null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='recipe_images')),
                ('url', models.URLField(max_length=128)),
                ('fish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whiskyouaway.Fish')),
            ],
        ),
        migrations.RemoveField(
            model_name='review',
            name='events',
        ),
        migrations.RemoveField(
            model_name='review',
            name='username',
        ),
        migrations.RemoveField(
            model_name='review',
            name='writtenReview',
        ),
        migrations.AddField(
            model_name='review',
            name='comment',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='date_posted',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(blank=True, default=5),
        ),
        migrations.AddField(
            model_name='review',
            name='recipe',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='whiskyouaway.Recipe'),
            preserve_default=False,
        ),
    ]
