# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-16 12:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whiskyouaway', '0008_auto_20190316_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('image', models.ImageField(upload_to='static/fish_images')),
            ],
        ),
        migrations.AlterField(
            model_name='recipe',
            name='fish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whiskyouaway.Categories'),
        ),
        migrations.DeleteModel(
            name='Fish',
        ),
    ]
