# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-16 12:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whiskyouaway', '0009_auto_20190316_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='Admin', max_length=128)),
                ('name', models.CharField(max_length=128, null=True)),
                ('description', models.CharField(max_length=9999, null=True)),
                ('avgRating', models.FloatField(null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='recipe_images')),
                ('url', models.URLField(max_length=128)),
                ('fish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whiskyouaway.Categories')),
            ],
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='fish',
        ),
        migrations.AlterField(
            model_name='review',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whiskyouaway.Events'),
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
