# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-16 14:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whiskyouaway', '0011_auto_20190316_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='recipe',
        ),
        migrations.AddField(
            model_name='review',
            name='events',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='whiskyouaway.Events'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categories',
            name='image',
            field=models.ImageField(upload_to='static/categories_images'),
        ),
    ]
